version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions-minor:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      github-actions-major:
        applies-to: version-updates
        update-types:
          - major
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 5
